name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            mateuskywalker90/fake-shop:latest
            mateuskywalker90/fake-shop:v${{ github.run_number }}

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Authenticate on AWS
        run: echo "Running the aws configure"
      - name: Configure the kubectl
        run: echo "Running the aws eks update-kubeconfig"
      - name: Deploying kubernetes manifest
        run: echo "Running the kebectl apply"
        
